fix the mount for cluster ca certs
openshift/cincinnati-operator pull request #161
Opened 2023-02-09 20:08 UTC by PratikMahajan

2023-02-09 21:50 UTC, PratikMahajan commented
/jira refresh

2023-02-09 21:55 UTC, LalatenduMohanty requested changes

2023-02-09 21:55 UTC, LalatenduMohanty commented on controllers/new.go
> +			MountPath: "/etc/pki/ca-trust/extracted/pem/ca-bundle.crt",
We still use the hard coded path here. Can we use a variable instead as we have the file name in `NameClusterCertConfigMapKey`?

2023-02-13 17:47 UTC, LalatenduMohanty commented
/jira refresh

2023-02-13 19:44 UTC, PratikMahajan commented
/override operator-e2e 
Using older version of cincinnati which does not have a multi-arch fix

2023-02-13 19:51 UTC, PratikMahajan reviewed
/override ci/prow/operator-e2e

2023-02-13 19:55 UTC, merged